name: Aktualizuj history.json

on:
  schedule:
    - cron: '0 22 * * *'   # codziennie o 22:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ustaw Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Zainstaluj zależności
        run: npm install node-fetch@2

      - name: Uruchom skrypt
        run: node js/update-history.js

      - name: Commit i push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add api/history.json
          git commit -m "Update history"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}